version: "3.8"

services:
  db:
    image: postgres
    container_name: db_kitten_show
    restart: unless-stopped    
    env_file:
      - .env    
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: app_kitten_show
    container_name: app_kitten_show
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head
      && uvicorn src.main:app --workers 1 --host=0.0.0.0 --port=8080"

volumes:
  pgdata: